### ISSUE TITLE
stylelint-config-airbnb is causing issues with npm for dependency resolution 

### ISSUE THREAD

**Issue by dishui** [airbnb/css#119]
when installing stylelint and stylelint-config-airbnb, I get the following npm Error:
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: stylelint-t2@1.0.0
npm ERR! Found: stylelint@8.4.0
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"*" from the root project
npm ERR!   peer stylelint@"^8.0.0" from stylelint-config-airbnb@0.0.0
npm ERR!   node_modules/stylelint-config-airbnb
npm ERR!     dev stylelint-config-airbnb@"*" from the root project
npm ERR!   1 more (stylelint-order)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev stylelint-config-prettier@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: stylelint@13.13.1
npm ERR! node_modules/stylelint
npm ERR!   peer stylelint@">=11.0.0" from stylelint-config-prettier@8.0.2
npm ERR!   node_modules/stylelint-config-prettier
npm ERR!     dev stylelint-config-prettier@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

remove the stylelint-config-airbnb, then no more problem. Of course, if one want to use stylelint-config-airbnb, then this is not a good solution.  That is why I am reporting the issue here

**Comment by ljharb** [comment]
It's saying the root project specifies `stylelint` at `*` (nothing should ever use a `*`), but v8.x is required by stylelint-config-airbnb - however, stylelint-config-prettier v8.0.2 requires stylelint v11+.

Thus, stylelint-config-airbnb is incompatible with that version of stylelint-config-prettier. You'll have to downgrade that one, or, give up using both of them together.
