### ISSUE TITLE
Translation welcome?

### ISSUE THREAD

**Issue by Zhangjd** [airbnb/css#15]
Hi, I have just translated this styleguide into Chinese Simplified version.

Would you like to append a translation list to the Readme? Just like the JavaScript styleguide.

[https://github.com/Zhangjd/css-style-guide](https://github.com/Zhangjd/css-style-guide)

**Comment by ljharb** [comment]
Thanks, that sounds like a great idea! If you could mimic the structure of the JS styleguide's translation list in a PR, I think it would be a very welcome addition.
