### ISSUE TITLE
We want to post blog about this css style guide.

### ISSUE THREAD

**Issue by nao215** [airbnb/css#24]
Hello!

I want to post this css style guide in Japanese as my companies tech blog.

This is our companies tech blog.
 [Recruit Sumai Company's Tech Blog](https://tech.recruit-sumai.co.jp/)

I think this is very good style guide so I want to spread a lot of Japanese!!
So can I post??

（´-`）.｡oO（and, is this right place to ask for this kind of question?)

**Comment by hshoff** [comment]
Hi @nao215, you're in the right place and go for it!
