### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by heldinz** [airbnb/css#62]
Would it be possible to add a license to this repository? We would like to use it as the basis for our own internal styleguide, but don't want to violate any copyright laws.

**Comment by DanielRuf** [comment]
It is probably licensed under the MIT license.

**Comment by DanielRuf** [comment]
See https://github.com/airbnb/javascript#license

**Comment by heldinz** [comment]
@DanielRuf I would hope that that is the case, but until a license is explicitly added to this repository, I have to consider it unlicensed.

**Comment by backwardok** [comment]
@heldinz are you looking for a particular file? The link that @DanielRuf provided is the license for this repo.

**Comment by lencioni** [comment]
@backwardok that link is for a different repo. We should add one to this repo though.

**Comment by backwardok** [comment]
oh hah! that's what I get for not paying attention to where I was posting :P too many repos

**Comment by lencioni** [comment]
Fixed by #63

**Comment by heldinz** [comment]
Thanks for adding this!
